export const FETCH_ZONES = 'FETCH_ZONES';
export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_SHARDS = 'FETCH_SHARDS';
export const FETCH_REALMS = 'FETCH_REALMS';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const LOADING_FINISHED = 'LOADING_FINISHED';

export const SHARD_UPDATED = 'SHARD_UPDATED';
export const SHARD_CONNECTED = 'SHARD_CONNECTED';
export const SHARD_DISCONNECTED = 'SHARD_DISCONNECTED';

export const SHARDS_SORTED = 'SHARDS_SORTED';
export const SHARDS_SELECTED = 'SHARDS_SELECTED';
export const SHARD_DESELECTED = 'SHARD_DESELECTED';

// old
export const UPDATE_REALM = 'UPDATE_REALM';
export const UPDATE_POSITIONS = 'UPDATE_POSITIONS';
export const UPDATING_POSITIONS_START = 'UPDATING_POSITIONS_START';
export const UPDATING_POSITIONS_END = 'UPDATING_POSITIONS_END';
