export const FETCH_REALMS = 'FETCH_REALMS';
export const FETCH_ISSUES = 'FETCH_ISSUES';

export const UPDATE_REALM = 'UPDATE_REALM';
export const UPDATE_POSITIONS = 'UPDATE_POSITIONS';
export const UPDATING_POSITIONS_START = 'UPDATING_POSITIONS_START';
export const UPDATING_POSITIONS_END = 'UPDATING_POSITIONS_END';