export const FETCH_ZONES = 'FETCH_ZONES';
export const FETCH_SHARDS = 'FETCH_SHARDS';
export const FETCH_ISSUES = 'FETCH_ISSUES';
export const LOADING_FINISHED = 'LOADING_FINISHED';

export const UPDATE_REALM = 'UPDATE_REALM';
export const UPDATE_POSITIONS = 'UPDATE_POSITIONS';
export const UPDATING_POSITIONS_START = 'UPDATING_POSITIONS_START';
export const UPDATING_POSITIONS_END = 'UPDATING_POSITIONS_END';
